[profile.default]
src = "contracts"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",

    "lido-core/=submodules/lido-core/contracts/",
    "contracts/openzeppelin/=submodules/lido-core/contracts/openzeppelin/",
    "contracts/common/=submodules/lido-core/contracts/common/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
