import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  slSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};

export default sidebars;
